---
- hosts: "{{ target | default('default') }}"
  become: yes

  roles:
    - codeyourinfra.docker_compose
    - codeyourinfra.maven

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - language-pack-pt
        - mysql-client
        - firefox
        - python3-pip
        - python-dev
        - libldap2-dev
        - libsasl2-dev
        - libssl-dev
        - ldap-utils

    - name: Install required python packages
      pip:
        name: "{{ item }}"
      loop:
        - docker
        - docker-compose
        - python-ldap

    - name: Disable Ubuntu unattended-upgrades during startup, to enable apt-get provisioning.
      ini_file:
        path: /lib/systemd/system/apt-daily.timer
        section: Timer
        option: Persistent
        value: false

    - name: Replace timesyncd with NTP
      include_tasks: timesync.yml

    - name: Get Ubuntu version
      shell: lsb_release -ds
      register: ubuntu_version_result
    - name: Show Ubuntu version
      debug:
        msg: "{{ ubuntu_version_result.stdout_lines[0] }}"
    - name: Store Ubuntu version
      copy:
        dest: ubuntu-version.txt
        content: "{{ ubuntu_version_result.stdout_lines[0] }}"
      delegate_to: localhost

    - name: Get Docker version
      shell: docker -v
      register: docker_version_result
    - name: Set Docker version fact
      set_fact:
        docker_version: "{{ docker_version_result.stdout_lines[0] | regex_search('([\\d.]+)') }}"
    - name: Show Docker version
      debug:
        msg: "{{ docker_version }}"
    - name: Store Docker version
      copy:
        dest: docker-version.txt
        content: "{{ docker_version }}"
      delegate_to: localhost

    - name: Get Docker Compose version
      shell: docker-compose -v
      register: docker_compose_version_result
    - name: Set Docker Compose version fact
      set_fact:
        docker_compose_version: "{{ docker_compose_version_result.stdout_lines[0] | regex_search('([\\d.]+)') }}"
    - name: Show Docker Compose version
      debug:
        msg: "{{ docker_compose_version }}"
    - name: Store Docker Compose version
      copy:
        dest: docker-compose-version.txt
        content: "{{ docker_compose_version }}"
      delegate_to: localhost

    - name: Get Java version
      shell: java -version
      register: java_version_result
    - name: Set Java version fact
      set_fact:
        java_version: "{{ java_version_result.stderr_lines[0] | regex_search('([\\d.]+_\\d*)') }}"
    - name: Show Java version
      debug:
        msg: "{{ java_version }}"
    - name: Store java version
      copy:
        dest: java-version.txt
        content: "{{ java_version }}"
      delegate_to: localhost

    - name: Get Maven version
      shell: mvn -version
      register: maven_version_result
    - name: Set Maven version fact
      set_fact:
        maven_version: "{{ maven_version_result.stdout_lines[0] | regex_search('([\\d.]+)') }}"
    - name: Show Maven version
      debug:
        msg: "{{ maven_version }}"
    - name: Store Maven version
      copy:
        dest: maven-version.txt
        content: "{{ maven_version }}"
      delegate_to: localhost

    - name: Minimize disk space
      script: minimize.sh
