---
- hosts: "{{ target | default('default') }}"
  become: yes
  roles:
    - codeyourinfra.docker_compose
    - codeyourinfra.maven
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - language-pack-pt
        - mysql-client
        - firefox
        - python3-pip
        - python-dev
        - libldap2-dev
        - libsasl2-dev
        - libssl-dev
        - ldap-utils
    - name: Install required python packages
      pip:
        name: "{{ item }}"
      loop:
        - docker
        - docker-compose
        - python-ldap
    - name: Prepare Docker for Prometheus monitoring
      copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
